name: az_travel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  form_field_validator: ^1.1.0
  get: 4.6.6
  google_sign_in: ^6.2.1
  hexcolor: ^3.0.1
  phosphor_flutter: ^2.0.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
