// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxMeVYZGOIHqwdxfBZPazzZ3WgaQUP7U',
    appId: '1:516917389194:web:300b42910eab4dd7904a73',
    messagingSenderId: '516917389194',
    projectId: 'aztravel-d5365',
    authDomain: 'aztravel-d5365.firebaseapp.com',
    storageBucket: 'aztravel-d5365.appspot.com',
    measurementId: 'G-QPJH723XWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cSw9RKqHfJfNDSMrtotDotApBF4N3yw',
    appId: '1:516917389194:android:b58efb0340243f9e904a73',
    messagingSenderId: '516917389194',
    projectId: 'aztravel-d5365',
    storageBucket: 'aztravel-d5365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPniDoFEVylj-UfD7Qsxyf9MFekEL8JQg',
    appId: '1:516917389194:ios:e5ba8e112fa414ea904a73',
    messagingSenderId: '516917389194',
    projectId: 'aztravel-d5365',
    storageBucket: 'aztravel-d5365.appspot.com',
    iosBundleId: 'com.example.azTravel',
  );
}
